### ISSUE TITLE
data-action may have stopped event

### ISSUE THREAD

**Issue by NakajimaTakuya** [hotwired/stimulus#380] opened 2021-02-19 09:17 UTC
Thank you for wonderful development experience.
I found one suspicious behavior today and will report it.

I was watching a single event propagating across multiple elements.
Then, after catching the event with data-action, the event did not bubble up.
I have prepared the code to reproduce it.
https://codepen.io/nazomikan/pen/QWGgoXO

Is this the correct behavior?
I expect a healthy bubble up.

**Comment by jmas** [comment] 2021-08-19 12:02
@NakajimaTakuya probably relevant issue https://github.com/hotwired/stimulus/issues/363

**Comment by dhh** [comment] 2021-08-30 14:18
Yes, duplicate of #363.

**Closed by dhh** 2021-08-30 14:18 UTC

**Comment by NakajimaTakuya** [comment] 2021-08-31 02:47
I see. Thank you. :)
