### ISSUE TITLE
connect() not work when change with javascript

### ISSUE THREAD

**Issue by karaka200** [hotwired/stimulus#555] opened 2022-06-30 21:23 UTC
Hi. I create a stimulus controller and use on a div element.
Now when change innerHTML of this div element with click on a button, text change but color not change to red and connect() not work.
```
<div data-controller="test">
    <span>This text color change to red</span>
    <button type="button" data-action="test#changeColor">click</button>
</div>
```
test_controller.js
```
...
connect() {
    this.element.style.color = "red";
}
changeColor(event) {
    this.element.innerHTML = "<span>HelloWorld!</span>"
}
...

```

**Comment by lb-** [comment] 2022-06-30 22:10
Hi @karaka200 it might be better to ask questions like this on Stackoverflow or the https://discuss.hotwired.dev/ only - looks like you have asked this here https://discuss.hotwired.dev/t/change-innerhtml-of-controller-with-javascript/4278

I will answer there as Github is better suited for bug reports.

**Comment by marcoroth** [comment] 2022-07-01 00:46
Closing this one since it's also a duplicate of #554

**Closed** 2022-07-01 00:46 UTC
